/*
QualDevLabsAuth

API for the QualDevLabs Auth library.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qualdevlabs_auth_go_client

import (
	"encoding/json"
)

// PasswordResetSchema struct for PasswordResetSchema
type PasswordResetSchema struct {
	Password string `json:"password"`
	RepeatPassword string `json:"repeatPassword"`
	Email string `json:"email"`
}

// NewPasswordResetSchema instantiates a new PasswordResetSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPasswordResetSchema(password string, repeatPassword string, email string) *PasswordResetSchema {
	this := PasswordResetSchema{}
	this.Password = password
	this.RepeatPassword = repeatPassword
	this.Email = email
	return &this
}

// NewPasswordResetSchemaWithDefaults instantiates a new PasswordResetSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPasswordResetSchemaWithDefaults() *PasswordResetSchema {
	this := PasswordResetSchema{}
	return &this
}

// GetPassword returns the Password field value
func (o *PasswordResetSchema) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *PasswordResetSchema) GetPasswordOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *PasswordResetSchema) SetPassword(v string) {
	o.Password = v
}

// GetRepeatPassword returns the RepeatPassword field value
func (o *PasswordResetSchema) GetRepeatPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RepeatPassword
}

// GetRepeatPasswordOk returns a tuple with the RepeatPassword field value
// and a boolean to check if the value has been set.
func (o *PasswordResetSchema) GetRepeatPasswordOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RepeatPassword, true
}

// SetRepeatPassword sets field value
func (o *PasswordResetSchema) SetRepeatPassword(v string) {
	o.RepeatPassword = v
}

// GetEmail returns the Email field value
func (o *PasswordResetSchema) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *PasswordResetSchema) GetEmailOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *PasswordResetSchema) SetEmail(v string) {
	o.Email = v
}

func (o PasswordResetSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["password"] = o.Password
	}
	if true {
		toSerialize["repeatPassword"] = o.RepeatPassword
	}
	if true {
		toSerialize["email"] = o.Email
	}
	return json.Marshal(toSerialize)
}

type NullablePasswordResetSchema struct {
	value *PasswordResetSchema
	isSet bool
}

func (v NullablePasswordResetSchema) Get() *PasswordResetSchema {
	return v.value
}

func (v *NullablePasswordResetSchema) Set(val *PasswordResetSchema) {
	v.value = val
	v.isSet = true
}

func (v NullablePasswordResetSchema) IsSet() bool {
	return v.isSet
}

func (v *NullablePasswordResetSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePasswordResetSchema(val *PasswordResetSchema) *NullablePasswordResetSchema {
	return &NullablePasswordResetSchema{value: val, isSet: true}
}

func (v NullablePasswordResetSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePasswordResetSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


