/*
QualDevLabsAuth

API for the QualDevLabs Auth library.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qualdevlabs_auth_go_client

import (
	"encoding/json"
)

// UserEmailSchema1 struct for UserEmailSchema1
type UserEmailSchema1 struct {
	Email string `json:"email"`
}

// NewUserEmailSchema1 instantiates a new UserEmailSchema1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserEmailSchema1(email string) *UserEmailSchema1 {
	this := UserEmailSchema1{}
	this.Email = email
	return &this
}

// NewUserEmailSchema1WithDefaults instantiates a new UserEmailSchema1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserEmailSchema1WithDefaults() *UserEmailSchema1 {
	this := UserEmailSchema1{}
	return &this
}

// GetEmail returns the Email field value
func (o *UserEmailSchema1) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UserEmailSchema1) GetEmailOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UserEmailSchema1) SetEmail(v string) {
	o.Email = v
}

func (o UserEmailSchema1) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["email"] = o.Email
	}
	return json.Marshal(toSerialize)
}

type NullableUserEmailSchema1 struct {
	value *UserEmailSchema1
	isSet bool
}

func (v NullableUserEmailSchema1) Get() *UserEmailSchema1 {
	return v.value
}

func (v *NullableUserEmailSchema1) Set(val *UserEmailSchema1) {
	v.value = val
	v.isSet = true
}

func (v NullableUserEmailSchema1) IsSet() bool {
	return v.isSet
}

func (v *NullableUserEmailSchema1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserEmailSchema1(val *UserEmailSchema1) *NullableUserEmailSchema1 {
	return &NullableUserEmailSchema1{value: val, isSet: true}
}

func (v NullableUserEmailSchema1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserEmailSchema1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


