/*
QualDevLabsAuth

API for the QualDevLabs Auth library.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package qualdevlabs_auth_go_client

import (
	"encoding/json"
)

// UserEmailSchema struct for UserEmailSchema
type UserEmailSchema struct {
	Email string `json:"email"`
}

// NewUserEmailSchema instantiates a new UserEmailSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserEmailSchema(email string) *UserEmailSchema {
	this := UserEmailSchema{}
	this.Email = email
	return &this
}

// NewUserEmailSchemaWithDefaults instantiates a new UserEmailSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserEmailSchemaWithDefaults() *UserEmailSchema {
	this := UserEmailSchema{}
	return &this
}

// GetEmail returns the Email field value
func (o *UserEmailSchema) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UserEmailSchema) GetEmailOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UserEmailSchema) SetEmail(v string) {
	o.Email = v
}

func (o UserEmailSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["email"] = o.Email
	}
	return json.Marshal(toSerialize)
}

type NullableUserEmailSchema struct {
	value *UserEmailSchema
	isSet bool
}

func (v NullableUserEmailSchema) Get() *UserEmailSchema {
	return v.value
}

func (v *NullableUserEmailSchema) Set(val *UserEmailSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableUserEmailSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableUserEmailSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserEmailSchema(val *UserEmailSchema) *NullableUserEmailSchema {
	return &NullableUserEmailSchema{value: val, isSet: true}
}

func (v NullableUserEmailSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserEmailSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


